services:
  hauler-ui:
    build: ..
    ports:
      - "8080:8080"   # Main UI
      - "5000:5000"   # Registry serve
      - "5001:5001"   # Fileserver serve
    volumes:
      - ./data:/data
    environment:
      - PORT=8080
